export const Users = [
    {
        id: 1,
        profilePicture: "assets/ava1.jpg",
        username: "Van Nham",
    },
    {
        id: 2,
        profilePicture: "assets/ava2.jpg",
        username: "Tran Lan",
    },
    {
        id: 3,
        profilePicture: "assets/ava3.jpg",
        username: "Le Thi",
    },
    {
        id: 4,
        profilePicture: "assets/ava4.png",
        username: "Ao Em",
    },
    {
        id: 5,
        profilePicture: "assets/gift.jpg",
        username: "Chua Mac",
    },
    {
        id: 6,
        profilePicture: "assets/Grosser_Panda.jpg",
        username: "Mot Lan",
    },
    {
        id: 7,
        profilePicture: "assets/ava5.jpg",
        username: "Xa Roi",
    },
    {
        id: 8,
        profilePicture: "assets/ava6.jpg",
        username: "Con Minh",
    },
    {
        id: 9,
        profilePicture: "assets/ava7.jpg",
        username: "anh Thoi",
    },
];

export const Posts = [
    {
        id: 1,
        desc: "Love for All hahaha",
        photo: "assets/ava1.jpg",
        date: "5 mins ago",
        userId: 1,
        like: 32,
        comment: 9,
    },
    {
        id: 2,
        photo: "assets/ava2.jpg",
        date: "10 mins ago",
        userId: 2,
        like: 2,
        comment: 10,
    },
    {
        id: 3,
        desc: "lan may khuat troi",
        photo: "assets/ava3.jpg",
        date: "15 mins ago",
        userId: 3,
        like: 9,
        comment: 18,
    },
    {
        id: 4,
        desc: "voi anh nhung ngay",
        photo: "assets/ava4.png",
        date: "20 mins ago",
        userId: 4,
        like: 16,
        comment: 1,
    },
    {
        id: 5,
        desc: "Love for All hahaha",
        photo: "assets/ava5.jpg",
        date: "1 mins ago",
        userId: 5,
        like: 1,
        comment: 0,
    },
    {
        id: 6,
        desc: "Love for All hahaha",
        photo: "assets/ava6.jpg",
        date: "5 mins ago",
        userId: 6,
        like: 32,
        comment: 9,
    },
    {
        id: 7,
        desc: "Love for All hahaha",
        photo: "assets/ava7.jpg",
        date: "5 mins ago",
        userId: 7,
        like: 32,
        comment: 9,
    },
    {
        id: 8,
        desc: "Love for All hahaha",
        photo: "assets/gif.jpg",
        date: "5 mins ago",
        userId: 8,
        like: 32,
        comment: 9,
    },
    {
        id: 9,
        desc: "Love for All hahaha",
        photo: "assets/Grosser_Panda.jpg",
        date: "5 mins ago",
        userId: 9,
        like: 32,
        comment: 9,
    },
]